name: Deploy to heroku API (staging)

on:
  push:
    branches:
      - staging
    paths:
      - "packages/backend"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
      - name: Release staging API
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_STAGING_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_APP_BASE: "packages/backend"
          DB_URL: ${{secrets.DB_URL}}
          COOKIE_KEY: ${{secrets.COOKIE_KEY}}
          CERAMIC_SEED: ${{secrets.CERAMIC_SEED}}
